import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Table from '../components/Table'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Development Technical Screening</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://dev.csesoc.org.au">CSESoc Development!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>components/Table.jsx</code>
        </p>
        <Table />
      </main>
    </div>
  )
}
