import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Table from './components/Table'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://dev.csesoc.org.au">CSESoc Development!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/components/Table.jsx</code>
        </p>
        <Table contents={{
          columnTitles: ['Alert', 'Issue', 'Occurences'],
          rowContents: [
            {
              alertType: 'food',
              alertText: 'good!',
              alertOccurence: []
            },
            {
              alertType: 'water',
              alertText: 'low',
              alertOccurence: [{anomaly: 'dropped to 10% below normal', date: '11/11/2022'}]
            },
            {
              alertType: 'shelter',
              alertText: 'terrible :(',
              alertOccurence: [{anomaly: 'slept on cold ground', date: '11/11/2022'}, {anomaly: 'slept on hard concrete', date: '13/11/2022'}]
            },
            {
              alertType: 'Done!',
              alertText: '<YOUR NAME>',
              alertOccurence: []
            }
          ]
        }} />
      </main>
    </div>
  )
}
